/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_SPATEM;
extern struct asn_TYPE_descriptor_s asn_DEF_PtActivation;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationControl;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_TrafficConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AccidentSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadworksSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanPresenceOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_WrongWayDrivingSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_AdhesionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_VisibilitySubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_AdverseWeatherCondition_PrecipitationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_SlowVehicleSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_StationaryVehicleSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanProblemSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyVehicleApproachingSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_DangerousCurveSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_SurfaceConditionSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_ObstacleOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_HazardousLocation_AnimalOnTheRoadSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_CollisionRiskSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalViolationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_RescueAndRecoveryWorkInProgressSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousEndOfQueueSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousSituationSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleBreakdownSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_PostCrashSubCauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_Curvature;
extern struct asn_TYPE_descriptor_s asn_DEF_CurvatureCalculationMode;
extern struct asn_TYPE_descriptor_s asn_DEF_Heading;
extern struct asn_TYPE_descriptor_s asn_DEF_LanePosition;
extern struct asn_TYPE_descriptor_s asn_DEF_ClosedLanes;
extern struct asn_TYPE_descriptor_s asn_DEF_PerformanceClass;
extern struct asn_TYPE_descriptor_s asn_DEF_Speed;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_EmbarkationStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_LongitudinalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_LateralAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_ExteriorLights;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousGoodsExtended;
extern struct asn_TYPE_descriptor_s asn_DEF_SpecialTransportType;
extern struct asn_TYPE_descriptor_s asn_DEF_LightBarSirenInUse;
extern struct asn_TYPE_descriptor_s asn_DEF_HeightLonCarr;
extern struct asn_TYPE_descriptor_s asn_DEF_PosLonCarr;
extern struct asn_TYPE_descriptor_s asn_DEF_PosCentMass;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestResponseIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimit;
extern struct asn_TYPE_descriptor_s asn_DEF_StationarySince;
extern struct asn_TYPE_descriptor_s asn_DEF_Temperature;
extern struct asn_TYPE_descriptor_s asn_DEF_TrafficRule;
extern struct asn_TYPE_descriptor_s asn_DEF_WheelBaseVehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_TurningRadius;
extern struct asn_TYPE_descriptor_s asn_DEF_PosFrontAx;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOfOccupants;
extern struct asn_TYPE_descriptor_s asn_DEF_PositioningSolutionType;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleIdentification;
extern struct asn_TYPE_descriptor_s asn_DEF_EnergyStorageType;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLength;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadType;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleRole;
extern struct asn_TYPE_descriptor_s asn_DEF_YawRate;
extern struct asn_TYPE_descriptor_s asn_DEF_RelevanceDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_RelevanceTrafficDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_TransmissionInterval;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidityDuration;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionID;
extern struct asn_TYPE_descriptor_s asn_DEF_ItineraryPath;
extern struct asn_TYPE_descriptor_s asn_DEF_Traces;
extern struct asn_TYPE_descriptor_s asn_DEF_NumberOfOccupants;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOfPillars;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictedTypes;
extern struct asn_TYPE_descriptor_s asn_DEF_EventHistory;
extern struct asn_TYPE_descriptor_s asn_DEF_ProtectedCommunicationZonesRSU;
extern struct asn_TYPE_descriptor_s asn_DEF_CenDsrcTollingZone;
extern struct asn_TYPE_descriptor_s asn_DEF_DigitalMap;
extern struct asn_TYPE_descriptor_s asn_DEF_OpeningDaysHours;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectionManeuverAssist_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectionTrajectory_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionState_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_MapData_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementEvent_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeAttributeSet_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_Position3D_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionUserType_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestorDescription_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalStatusPackage_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_MapData;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMcorrections;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalRequestMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalStatusMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_EuVehicleCategoryCode;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module SPATEM-PDU-Descriptions in ./asn1/SPATEM-PDU-Descriptions.asn */
	&asn_DEF_SPATEM,	
	/* From module ITS-Container in ./asn1/ITS-Container.asn */
	&asn_DEF_PtActivation,	
	&asn_DEF_AccelerationControl,	
	&asn_DEF_CauseCode,	
	&asn_DEF_TrafficConditionSubCauseCode,	
	&asn_DEF_AccidentSubCauseCode,	
	&asn_DEF_RoadworksSubCauseCode,	
	&asn_DEF_HumanPresenceOnTheRoadSubCauseCode,	
	&asn_DEF_WrongWayDrivingSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_AdhesionSubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_VisibilitySubCauseCode,	
	&asn_DEF_AdverseWeatherCondition_PrecipitationSubCauseCode,	
	&asn_DEF_SlowVehicleSubCauseCode,	
	&asn_DEF_StationaryVehicleSubCauseCode,	
	&asn_DEF_HumanProblemSubCauseCode,	
	&asn_DEF_EmergencyVehicleApproachingSubCauseCode,	
	&asn_DEF_HazardousLocation_DangerousCurveSubCauseCode,	
	&asn_DEF_HazardousLocation_SurfaceConditionSubCauseCode,	
	&asn_DEF_HazardousLocation_ObstacleOnTheRoadSubCauseCode,	
	&asn_DEF_HazardousLocation_AnimalOnTheRoadSubCauseCode,	
	&asn_DEF_CollisionRiskSubCauseCode,	
	&asn_DEF_SignalViolationSubCauseCode,	
	&asn_DEF_RescueAndRecoveryWorkInProgressSubCauseCode,	
	&asn_DEF_DangerousEndOfQueueSubCauseCode,	
	&asn_DEF_DangerousSituationSubCauseCode,	
	&asn_DEF_VehicleBreakdownSubCauseCode,	
	&asn_DEF_PostCrashSubCauseCode,	
	&asn_DEF_Curvature,	
	&asn_DEF_CurvatureCalculationMode,	
	&asn_DEF_Heading,	
	&asn_DEF_LanePosition,	
	&asn_DEF_ClosedLanes,	
	&asn_DEF_PerformanceClass,	
	&asn_DEF_Speed,	
	&asn_DEF_DriveDirection,	
	&asn_DEF_EmbarkationStatus,	
	&asn_DEF_LongitudinalAcceleration,	
	&asn_DEF_LateralAcceleration,	
	&asn_DEF_VerticalAcceleration,	
	&asn_DEF_ExteriorLights,	
	&asn_DEF_DangerousGoodsExtended,	
	&asn_DEF_SpecialTransportType,	
	&asn_DEF_LightBarSirenInUse,	
	&asn_DEF_HeightLonCarr,	
	&asn_DEF_PosLonCarr,	
	&asn_DEF_PosCentMass,	
	&asn_DEF_RequestResponseIndication,	
	&asn_DEF_SpeedLimit,	
	&asn_DEF_StationarySince,	
	&asn_DEF_Temperature,	
	&asn_DEF_TrafficRule,	
	&asn_DEF_WheelBaseVehicle,	
	&asn_DEF_TurningRadius,	
	&asn_DEF_PosFrontAx,	
	&asn_DEF_PositionOfOccupants,	
	&asn_DEF_PositioningSolutionType,	
	&asn_DEF_VehicleIdentification,	
	&asn_DEF_EnergyStorageType,	
	&asn_DEF_VehicleLength,	
	&asn_DEF_VehicleWidth,	
	&asn_DEF_EmergencyPriority,	
	&asn_DEF_RoadType,	
	&asn_DEF_SteeringWheelAngle,	
	&asn_DEF_VehicleRole,	
	&asn_DEF_YawRate,	
	&asn_DEF_RelevanceDistance,	
	&asn_DEF_RelevanceTrafficDirection,	
	&asn_DEF_TransmissionInterval,	
	&asn_DEF_ValidityDuration,	
	&asn_DEF_ActionID,	
	&asn_DEF_ItineraryPath,	
	&asn_DEF_Traces,	
	&asn_DEF_NumberOfOccupants,	
	&asn_DEF_PositionOfPillars,	
	&asn_DEF_RestrictedTypes,	
	&asn_DEF_EventHistory,	
	&asn_DEF_ProtectedCommunicationZonesRSU,	
	&asn_DEF_CenDsrcTollingZone,	
	&asn_DEF_DigitalMap,	
	&asn_DEF_OpeningDaysHours,	
	/* From module AddGrpC in ./asn1/ISO-19091.asn */
	&asn_DEF_ConnectionManeuverAssist_addGrpC,	
	&asn_DEF_ConnectionTrajectory_addGrpC,	
	&asn_DEF_IntersectionState_addGrpC,	
	&asn_DEF_LaneAttributes_addGrpC,	
	&asn_DEF_MapData_addGrpC,	
	&asn_DEF_MovementEvent_addGrpC,	
	&asn_DEF_NodeAttributeSet_addGrpC,	
	&asn_DEF_Position3D_addGrpC,	
	&asn_DEF_RestrictionUserType_addGrpC,	
	&asn_DEF_RequestorDescription_addGrpC,	
	&asn_DEF_SignalStatusPackage_addGrpC,	
	/* From module DSRC in ./asn1/ISO-19091.asn */
	&asn_DEF_MapData,	
	&asn_DEF_RTCMcorrections,	
	&asn_DEF_SignalRequestMessage,	
	&asn_DEF_SignalStatusMessage,	
	/* From module ElectronicRegistrationIdentificationVehicleDataModule in ./asn1/ISO-24534-3.asn */
	&asn_DEF_EuVehicleCategoryCode,	
	0
};

